# Generated by Django 2.2.6 on 2020-06-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('unique_id', models.IntegerField(default=None, unique=True)),
                ('data_structure', models.IntegerField(default=None)),
                ('database', models.IntegerField(default=None)),
                ('web_technology', models.IntegerField(default=None)),
                ('cloud', models.IntegerField(default=None)),
                ('data_science', models.IntegerField(default=None)),
            ],
        ),
    ]
