# Generated by Django 2.2.6 on 2020-07-01 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentmarksapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None, unique=True)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmarksapi.Student_marks')),
            ],
        ),
    ]
