# Generated by Django 2.2.6 on 2020-07-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmarksapi', '0002_request_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_counter',
            name='counter_req',
            field=models.IntegerField(default=None),
        ),
    ]
