# Generated by Django 2.2.6 on 2020-07-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmarksapi', '0006_auto_20200702_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_counter',
            name='service',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
