# Generated by Django 2.2.6 on 2020-07-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmarksapi', '0007_request_counter_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_counter',
            name='service',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
