# Generated by Django 2.2.6 on 2020-07-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmarksapi', '0008_auto_20200702_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_counter',
            name='service',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
