# Generated by Django 2.2.6 on 2020-07-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmarksapi', '0009_auto_20200702_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_counter',
            name='service',
        ),
        migrations.AddField(
            model_name='request_counter',
            name='service_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
